### ISSUE TITLE
[1.12.2]Not compatible with later versions of Mekanism Generators

### ISSUE THREAD

**Issue by sddsd2332** [igentuman/BettefFusionReactor#16]
As the title suggests, mcmod.info set Mekanism Generators to only work in [9.8.3.390](https://github.com/igentuman/Better-Fusion-Reactor/blob/a108560ce482bca0fea2a9d89b1d2c666b0b83ab/src/main/resources/mcmod.info#L13-L17), and will not work if you switch to Mekanism branch [Mekanism 1.12.2 Community Edition](https://www.curseforge.com/minecraft/mc-mods/mekanism-1-12-2-ce).
Because the version number of Mekanism 1.12.2 Community Edition is 9.12.+

Very simple handling:
Remove `@[1.12.2-9.8.3.390]`to be compatible with other versions.

**Comment by igentuman** [comment]
Already did that in the latest update
