### ISSUE TITLE
[1.12.2]The Injection text box can write more than 98 settings

### ISSUE THREAD

**Issue by sddsd2332** [igentuman/BettefFusionReactor#17]
As the title indicates,
The injection text can be written to 998
In the GUI[setMaxStringLength(3)](https://github.com/igentuman/Better-Fusion-Reactor/blob/a108560ce482bca0fea2a9d89b1d2c666b0b83ab/src/main/java/igentuman/bfr/client/gui/GuiReactorFuel.java#L117),This should be [2](https://github.com/mekanism/Mekanism/blob/84a5196136be8b3300bdc554e81a677bb53eabc5/src/main/java/mekanism/generators/client/gui/GuiReactorFuel.java#L116), not 3.

**Comment by igentuman** [comment]
As this affects only client side i see no reasons for limmiting input back to 98. And mekanism has no such limitation in new versions.
But i've decided to add config option for that. So you can define it if you want. Default limit is 998
