### ISSUE TITLE
6x ore production for 1.17+

### ISSUE THREAD

**Issue by SPancerfaustyna** [igentuman/BettefFusionReactor#20]
when minecraft introduced raw form for every ore. This allowed mekanis with fortune 3 to make 6.6-13.3x ore processing and now irradiating ore for 6x thas't sound that great. Maybe consider updating this feature for newer version.

**Comment by igentuman** [comment]
13.3x u serious? This is ridiculous.
Ok then we need to change loot tables for irradiated ores. So it will drop 50% plus raw chunks.
