### ISSUE TITLE
LoaderExceptionModCrash

### ISSUE THREAD

**Issue by baifeiajdj** [igentuman/BettefFusionReactor#21]
[crash-2024-03-03_12.24.33-client.txt](https://github.com/igentuman/Better-Fusion-Reactor/files/14471774/crash-2024-03-03_12.24.33-client.txt)
version:1.12.2
Mekanism:Mekanism CE Unofficial-All-9.8.11.185.jar

**Comment by igentuman** [comment]
Please checkout latest build

**Comment by igentuman** [comment]
https://github.com/igentuman/Better-Fusion-Reactor/actions/runs/8130378054
