### ISSUE TITLE
laser focus matrix breaks reactor

### ISSUE THREAD

**Issue by DiglisTheIII** [igentuman/BettefFusionReactor#22]
adding the laser focus matrix to the fusion reactor causes it to not become a multiblock. the crafting recipe in JEI also doesn't automatically pull the reactor glass, nor does it show up in JEI

**Comment by igentuman** [comment]
It would be nice to have a version. And maybe some logs attached

**Comment by DiglisTheIII** [comment]
Ahh my bad, I was really tired when I made this. Can't get the logs or
version since it was deleted from the server, but I do know it was the
latest release for 1.20.1.

**Comment by igentuman** [comment]
Just checked. Fusion reactor works if built of BFR blocks.  JEI shows recipes for laser focus matrix from BFR.
Anyways. I think i need to re-work it
