### ISSUE TITLE
Minecraft 1.12.2 error while adjusting reactivity on OpenComputers.

### ISSUE THREAD

**Issue by Kenley-M** [igentuman/BettefFusionReactor#23]
![image](https://github.com/igentuman/Better-Fusion-Reactor/assets/92249212/209dffad-5fbb-48cd-8b81-9b7959a5ff5e)
![image](https://github.com/igentuman/Better-Fusion-Reactor/assets/92249212/a37a5f79-13d7-4200-bd55-83fbe3efcbf6)

Edit: solved.

fix: input an hexadecimal number to the function and it will work. Example: 15.0, 15.5, 0.1 NOT 15

for the developer: Please add some sort of response example: awaited number got integer

**Comment by igentuman** [comment]
@KenleyundLeon hey. Why did you close the bug? If issue exists, i need to fix it

**Comment by Kenley-M** [comment]
The fix is to input an hexadecimal number example: 15.0 NOT 15 due to java awaiting an Number value rather than a integer value.
