### ISSUE TITLE
[Suggestion]Explode the reactor when ERRORLEVEL reaches 100%

### ISSUE THREAD

**Issue by tong-ge** [igentuman/BettefFusionReactor#6]
Most of the nuclear reactors in Minecraft could explode when poorly managed.So should Mekanism Fusion.
*“Art is explosion!”--Deidara，NARUTO*

**Comment by igentuman** [comment]
Will add a config option for that

**Comment by tong-ge** [comment]
OK.Better to do it for both 1.12 and 1.16 versions.

**Comment by igentuman** [comment]
Done for 1.12.2 version

**Comment by tong-ge** [comment]
Thanks.But,the explosion is only one TNT size?It's too small for a nuclear stuff.

**Comment by igentuman** [comment]
Fusion reactors are not exploading IRL. 
Also some big booms can bring us to additional issues.

**Comment by tong-ge** [comment]
But most of the fusion devices do explode and do it really big.(e.g Big Ivan)
